package main

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
	"sort"
)

// BoardEffectsData holds board effect parameters loaded from data/board_effects.json.
// Generated by scripts/sync_holodori.py from HolodoriDB SkillTreeNode + SkillTreeEffect.
type BoardEffectsData struct {
	CdReduce struct {
		PerNodePermil int `json:"per_node_permil"`
		MaxNodes      int `json:"max_nodes"`
		TotalPermil   int `json:"total_permil"`
		Nodes         []struct {
			NodeGroup  string `json:"node_group"`
			ValuePermil int   `json:"value_permil"`
			Grade      int    `json:"grade"`
			CostPoints int    `json:"cost_points"`
			CostItems  []struct {
				ID       string `json:"id"`
				Quantity int    `json:"quantity"`
			} `json:"cost_items"`
		} `json:"nodes"`
	} `json:"cd_reduce"`
	ActivationUp struct {
		TotalPermil int `json:"total_permil"`
		Nodes       []struct {
			NodeGroup   string `json:"node_group"`
			ValuePermil int    `json:"value_permil"`
			Grade       int    `json:"grade"`
			CostPoints  int    `json:"cost_points"`
		} `json:"nodes"`
	} `json:"activation_up"`
}

// fallback constants (used if board_effects.json is not available)
const (
	fallbackCdReducePerNode         = 40
	fallbackCdReduceMaxNodes        = 3
	fallbackActivationUpTotalPermil = 300
)

var boardEffects *BoardEffectsData

func loadBoardEffects(dataDir string) {
	path := filepath.Join(dataDir, "data", "board_effects.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var be BoardEffectsData
	if json.Unmarshal(data, &be) == nil {
		boardEffects = &be
	}
}

func getCdReducePerNode() int {
	if boardEffects != nil && boardEffects.CdReduce.PerNodePermil > 0 {
		return boardEffects.CdReduce.PerNodePermil
	}
	return fallbackCdReducePerNode
}

func getCdReduceMaxNodes() int {
	if boardEffects != nil && boardEffects.CdReduce.MaxNodes > 0 {
		return boardEffects.CdReduce.MaxNodes
	}
	return fallbackCdReduceMaxNodes
}

func getActivationUpTotalPermil() int {
	if boardEffects != nil && boardEffects.ActivationUp.TotalPermil > 0 {
		return boardEffects.ActivationUp.TotalPermil
	}
	return fallbackActivationUpTotalPermil
}

// OptimizeBoardForTeam optimizes per-member cdReduce node counts to
// maximize LiveScoreIndex. activationUp is always fully unlocked.
// Search space: (maxNodes+1)^5 combinations.
//
// Uses a fast evaluation path: Active probabilities are pre-computed for all
// (member × cdLevel × scoreEvent) combinations, then the 1024-combo search
// uses only array lookups and arithmetic instead of regenerating timelines.
func OptimizeBoardForTeam(
	team [5]*Card,
	totalPower, songDuration float64,
	timeline *SongTimeline,
	scoreEvents []ScoreEvent,
	alwaysOnSupport float64,
) *BoardOptResult {
	if len(scoreEvents) == 0 {
		return nil
	}

	cdPerNode := getCdReducePerNode()
	maxNodes := getCdReduceMaxNodes()
	actUpPermil := getActivationUpTotalPermil()

	// Baseline evaluation (full, for the result)
	var baseConfigs [5]*BoardConfig
	for i := 0; i < 5; i++ {
		baseConfigs[i] = &BoardConfig{
			ActivationUpPermil: actUpPermil,
		}
	}
	baseResult := EvaluateFullTimelineWithBoard(team, totalPower, songDuration, timeline, scoreEvents, alwaysOnSupport, baseConfigs)

	// --- Pre-compute fixed data ---
	spWindows := generateSpecialWindows(team, timeline)
	typeCounts := countTypes(team)
	nEvents := len(scoreEvents)
	nLevels := maxNodes + 1

	// Resolve scoreUp per card and determine sort order (descending scoreUp).
	// The sort order is independent of board config.
	type cardInfo struct {
		origIdx int
		scoreUp float64
	}
	cardInfos := make([]cardInfo, 5)
	for i, card := range team {
		su := card.CenterSkill.ScoreUp
		if card.CenterSkill.Condition != nil && checkCenterTypeCondition(card.CenterSkill.Condition, typeCounts) {
			if card.CenterSkill.ConditionalScoreUp != nil {
				su = *card.CenterSkill.ConditionalScoreUp
			}
		}
		cardInfos[i] = cardInfo{origIdx: i, scoreUp: su}
	}
	sort.Slice(cardInfos, func(i, j int) bool {
		return cardInfos[i].scoreUp > cardInfos[j].scoreUp
	})

	// Pre-compute per-event fixed values: weight, comboMultiplier, scoreSupportAtTime
	type eventFixed struct {
		weight          float64
		comboWeight     float64 // weight * comboMultiplier
		supportFactor   float64 // 1 + (alwaysOnSupport + spSupport) / 100
	}
	evFixed := make([]eventFixed, nEvents)
	for ei := range scoreEvents {
		ev := &scoreEvents[ei]
		w := ev.Weight
		if w <= 0 {
			w = 1.0
		}
		spSupport := 0.0
		if spWindows != nil {
			spSupport = scoreSupportAtTime(spWindows, ev.Time)
		}
		combo := comboMultiplier(ev.ComboIndex)
		evFixed[ei] = eventFixed{
			weight:        w,
			comboWeight:   w * combo,
			supportFactor: 1.0 + (alwaysOnSupport+spSupport)/100.0,
		}
	}

	// --- Phase 1: Pre-compute Active probabilities ---
	// activeProb[sortedCardIdx][cdLevel][eventIdx] = probability that this card is active
	// Only 5 * nLevels = 20 sets of ActiveAttempts need to be generated.
	activeProb := make([][][]float64, 5)
	for si := 0; si < 5; si++ {
		ci := cardInfos[si].origIdx
		card := team[ci]
		activeProb[si] = make([][]float64, nLevels)
		for lv := 0; lv < nLevels; lv++ {
			cfg := &BoardConfig{
				CdReducePermil:     lv * cdPerNode,
				ActivationUpPermil: actUpPermil,
			}
			attempts := generateActiveAttemptsWithBoard(card, ci, songDuration, 0, spWindows, typeCounts, cfg)
			state := &activeCardState{attempts: attempts}
			probs := make([]float64, nEvents)
			for ei := range scoreEvents {
				probs[ei] = activeProbAtTime(state, scoreEvents[ei].Time)
			}
			activeProb[si][lv] = probs
		}
	}

	// scoreUps in sorted order
	var scoreUps [5]float64
	for si := 0; si < 5; si++ {
		scoreUps[si] = cardInfos[si].scoreUp
	}

	// --- Phase 2-4: Fast search ---
	bestLSI := baseResult.LiveScoreIndex
	var bestLevels [5]int

	totalCombos := 1
	for i := 0; i < 5; i++ {
		totalCombos *= nLevels
	}

	// Map from sorted card index to the cdLevel for this combo
	var levels [5]int

	for combo := 0; combo < totalCombos; combo++ {
		// Extract levels (sorted card order matches cardInfos order)
		rem := combo
		for si := 0; si < 5; si++ {
			levels[si] = rem % nLevels
			rem /= nLevels
		}

		// Compute LiveScoreIndex using only cached probabilities
		relativeSongScore := 0.0
		for ei := 0; ei < nEvents; ei++ {
			// E[max] calculation: sorted by scoreUp descending
			emax := 0.0
			probNoneHigher := 1.0
			for si := 0; si < 5; si++ {
				p := activeProb[si][levels[si]][ei]
				emax += scoreUps[si] * p * probNoneHigher
				probNoneHigher *= (1.0 - p)
			}

			ef := &evFixed[ei]
			skillMultiplier := (1.0 + emax/100.0) * ef.supportFactor
			relativeSongScore += ef.comboWeight * skillMultiplier
		}

		lsi := totalPower * relativeSongScore
		if lsi > bestLSI {
			bestLSI = lsi
			// Map sorted levels back to original card order
			for si := 0; si < 5; si++ {
				bestLevels[cardInfos[si].origIdx] = levels[si]
			}
		}
	}

	// --- Final: full evaluation for best config to get overlap loss ---
	var bestConfigs [5]*BoardConfig
	for i := 0; i < 5; i++ {
		bestConfigs[i] = &BoardConfig{
			CdReducePermil:     bestLevels[i] * cdPerNode,
			ActivationUpPermil: actUpPermil,
		}
	}
	bestResult := EvaluateFullTimelineWithBoard(team, totalPower, songDuration, timeline, scoreEvents, alwaysOnSupport, bestConfigs)

	var members [5]BoardMemberResult
	for i := 0; i < 5; i++ {
		members[i] = BoardMemberResult{
			CdReduceNodes: bestLevels[i],
			CardID:        team[i].ID,
		}
	}

	return &BoardOptResult{
		Members:       members,
		BaselineLoss:  fixedFloat(baseResult.ActiveOverlapLoss * 100),
		OptimizedLoss: fixedFloat(bestResult.ActiveOverlapLoss * 100),
		BaselineLSI:   int(math.Round(baseResult.LiveScoreIndex)),
		OptimizedLSI:  int(math.Round(bestResult.LiveScoreIndex)),
	}
}
