package main

import (
	"encoding/json"
	"math"
	"os"
	"path/filepath"
)

// BoardEffectsData holds board effect parameters loaded from data/board_effects.json.
// Generated by scripts/sync_holodori.py from HolodoriDB SkillTreeNode + SkillTreeEffect.
type BoardEffectsData struct {
	CdReduce struct {
		PerNodePermil int `json:"per_node_permil"`
		MaxNodes      int `json:"max_nodes"`
		TotalPermil   int `json:"total_permil"`
		Nodes         []struct {
			NodeGroup  string `json:"node_group"`
			ValuePermil int   `json:"value_permil"`
			Grade      int    `json:"grade"`
			CostPoints int    `json:"cost_points"`
			CostItems  []struct {
				ID       string `json:"id"`
				Quantity int    `json:"quantity"`
			} `json:"cost_items"`
		} `json:"nodes"`
	} `json:"cd_reduce"`
	ActivationUp struct {
		TotalPermil int `json:"total_permil"`
		Nodes       []struct {
			NodeGroup   string `json:"node_group"`
			ValuePermil int    `json:"value_permil"`
			Grade       int    `json:"grade"`
			CostPoints  int    `json:"cost_points"`
		} `json:"nodes"`
	} `json:"activation_up"`
}

// fallback constants (used if board_effects.json is not available)
const (
	fallbackCdReducePerNode         = 40
	fallbackCdReduceMaxNodes        = 3
	fallbackActivationUpTotalPermil = 300
)

var boardEffects *BoardEffectsData

func loadBoardEffects(dataDir string) {
	path := filepath.Join(dataDir, "data", "board_effects.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	var be BoardEffectsData
	if json.Unmarshal(data, &be) == nil {
		boardEffects = &be
	}
}

func getCdReducePerNode() int {
	if boardEffects != nil && boardEffects.CdReduce.PerNodePermil > 0 {
		return boardEffects.CdReduce.PerNodePermil
	}
	return fallbackCdReducePerNode
}

func getCdReduceMaxNodes() int {
	if boardEffects != nil && boardEffects.CdReduce.MaxNodes > 0 {
		return boardEffects.CdReduce.MaxNodes
	}
	return fallbackCdReduceMaxNodes
}

func getActivationUpTotalPermil() int {
	if boardEffects != nil && boardEffects.ActivationUp.TotalPermil > 0 {
		return boardEffects.ActivationUp.TotalPermil
	}
	return fallbackActivationUpTotalPermil
}

// OptimizeBoardForTeam optimizes per-member cdReduce node counts to
// maximize LiveScoreIndex. activationUp is always fully unlocked.
// Search space: (maxNodes+1)^5 combinations.
func OptimizeBoardForTeam(
	team [5]*Card,
	totalPower, songDuration float64,
	timeline *SongTimeline,
	scoreEvents []ScoreEvent,
	alwaysOnSupport float64,
) *BoardOptResult {
	if len(scoreEvents) == 0 {
		return nil
	}

	cdPerNode := getCdReducePerNode()
	maxNodes := getCdReduceMaxNodes()
	actUpPermil := getActivationUpTotalPermil()

	var baseConfigs [5]*BoardConfig
	for i := 0; i < 5; i++ {
		baseConfigs[i] = &BoardConfig{
			ActivationUpPermil: actUpPermil,
		}
	}
	baseResult := EvaluateFullTimelineWithBoard(team, totalPower, songDuration, timeline, scoreEvents, alwaysOnSupport, baseConfigs)

	bestLSI := baseResult.LiveScoreIndex
	bestLoss := baseResult.ActiveOverlapLoss
	var bestLevels [5]int

	totalCombos := 1
	for i := 0; i < 5; i++ {
		totalCombos *= (maxNodes + 1)
	}

	for combo := 0; combo < totalCombos; combo++ {
		var configs [5]*BoardConfig
		var levels [5]int
		rem := combo
		for i := 0; i < 5; i++ {
			level := rem % (maxNodes + 1)
			rem /= (maxNodes + 1)
			levels[i] = level
			configs[i] = &BoardConfig{
				CdReducePermil:     level * cdPerNode,
				ActivationUpPermil: actUpPermil,
			}
		}

		result := EvaluateFullTimelineWithBoard(team, totalPower, songDuration, timeline, scoreEvents, alwaysOnSupport, configs)
		if result.LiveScoreIndex > bestLSI {
			bestLSI = result.LiveScoreIndex
			bestLoss = result.ActiveOverlapLoss
			bestLevels = levels
		}
	}

	var members [5]BoardMemberResult
	for i := 0; i < 5; i++ {
		members[i] = BoardMemberResult{
			CdReduceNodes: bestLevels[i],
			CardID:        team[i].ID,
		}
	}

	return &BoardOptResult{
		Members:       members,
		BaselineLoss:  fixedFloat(baseResult.ActiveOverlapLoss * 100),
		OptimizedLoss: fixedFloat(bestLoss * 100),
		BaselineLSI:   int(math.Round(baseResult.LiveScoreIndex)),
		OptimizedLSI:  int(math.Round(bestLSI)),
	}
}
